### ISSUE TITLE
Tool Chain Setup

### ISSUE THREAD

**Issue by rahulraveendran15-coder** [lowRISC/lowrisc-toolchains#36]
Hi,
I need a help on the following
If I am using the pre-built tool chain can I use "https://github.com/lowRISC/lowrisc-toolchains/releases/tag/20200904-1" the following tool chain version? Does the lowrisc-toolchain-gcc-rv32imcb-20200904-1.tar.xz
 support both bit manipulation extension and normal operation? OR do I need to download both tar files there one for bit manip and other for normal operation?
How it will decide which tool chain has to invoke either with bit manipulation or another?
I cannot use the pre built tool chain whatever is mentioned here because I am using centos 7 and the glibc is not of 2.7 version, So how can I build the tool chain with the specific release from the source code?

**Comment by lenary** [comment]
> Does the lowrisc-toolchain-gcc-rv32imcb-20200904-1.tar.xz support both bit manipulation extension and normal operation?

The compiler accepts flags (`-march=rv32imcb`) to enable generating executables with bit manipulation instructions. The libraries are generated without these flags, so you can use `-march=rv32imc` to generate executables that only use IMC instructions.

You only need to download one file.

The instructions for how these toolchains are built are in the `azure-pipelines.yml` file, and the shell scripts it references, including invoking crosstool-ng. You should be able to use our crosstool-ng configuration and our patches to build an equivalent toolchain (including pulling exactly the version of crosstool-ng specified in the repository). 

At some point we are intending to build this on an old-enough version of CentOS that it should work on any modern linux, but I don't have the time to do this immediately.

**Comment by rahulraveendran15-coder** [comment]
So which one should I download
lowrisc-toolchain-gcc-rv32imcb-20200904-1.tar.xz or lowrisc-toolchain-gcc-rv32imc-20200904-1.tar.xz

Basically what is the difference between both these tar files?
I am not planning to buld any tool chain and directly downloading  the prebuilt the tar I am thinking of

**Comment by lenary** [comment]
If you need bitmanip support, download the `rv32imcb` toolchain. The other toolchain (`rv32imc`) does not support bit manipulation instructions.

Both toolchains support restricting the instruction set to only `rv32imc`.

**Comment by rahulraveendran15-coder** [comment]
Sorry to bother you again I am new to this setup, Could you please help me on the below points
(1) The other toolchain (rv32imc) does not support bit manipulation instructions -- if I am downloading the rv32imc tool chain and compiling the c file with `march=rv32imcb` will it be fine? Because in the first point you mentioned the compiler support -march flags. If so what is the use of separate `rv32imcb` toolchain, i can download `rv32imc` tool chain and compile with `-march=rv32imcb`
(2) I need to use rv32e compilation also so any of these tool chains in this releases will support rv32e, in order to compile a file with rv32e what should I need to do which tool chain I need to download?

**Comment by lenary** [comment]
1. Only the `imcb` toolchains are tested to be able to emit B instructions. RISC-V compilers allow you to enable/disable any extensions they support, but the `imc` toolchains DO NOT SUPPORT bit manipulation. The `imc` toolchain has no idea that the B extension even exists.

This is because the B extension is not ratified, so there is no `b` support in mainline GCC, and we had to apply specific patches for the `imcb` toolchains.

I'm going to be explicit about this: you seem to want to emit bit manipulation instructions. Download the `rv32imcb` toolchains.

2. lowRISC does not use `rv32e` setups in its work, so we do not test these compilers with rv32e, and that configuration is entirely unsupported. I cannot tell you whether it works or not, let alone ensure it does. I can tell you that Clang/LLVM has never supported rv32e, I am not up to date with the situation with GCC, because we do not need it for our work.

**Comment by rahulraveendran15-coder** [comment]
Hi,
Thank you very much for making it clear
I will download `rv32imcb` tool chain. One more concern is that By default for `rv32imcb` toolchain does the bitmanip is enabled or not could you please confirm else I need to add `-march=rv32imcb` in my compilation command to enable it.

**Comment by lenary** [comment]
You have to pass the flags.
