### ISSUE TITLE
GCC/binutils: Apply bitmanip patches

### ISSUE THREAD

**Issue by imphil** [lowRISC/lowrisc-toolchains#9]
Apply patches from https://github.com/riscv/riscv-bitmanip/tree/master/tools to our GCC/binutils build. We probably need to extract the patches, and apply them through crosstool-ng.

**Comment by luismarques** [comment]
The binutils bitmanip fork seems to have been done a while after binutils 2.32, but a bit before 2.33. The ct-ng binary used in this repo only supports binutils 2.32. A patch to go from binutils 2.32 to 2.33 or to the fork head is something like 44 MB. I'm not sure that's desirable (due to the size and further potential for incompatibilities with the rest of the toolchain tools).
One alternative is to upgrade ct-ng, and rebase the bitmanip fork on top of 2.33, which reduces the patch size to something like 2.7 MB. I have done that rebase (with `-Xtheirs` to resolve some large but irrelevant conflicts), but that also introduces its own risks (I might have messed up the rebase).
Another option is to rebase/backport to 2.32, but there are merge conflicts and those seem even trickier to solve. I'm evaluating the best way forward.
Do you have any opinion on this)

**Comment by imphil** [comment]
Let's keep the patch to a minimum covering bitmanip, and ideally nothing beyond that. We can pick a more or less arbitrary binutils baseline through ct-ng, so try to use the one that is closest to something relatively recent in the other repo.

**Comment by luismarques** [comment]
The closest binutils in ct-ng is 2.33 (but choosing that version requires upgrading the ct-ng built per this repo). There seems to have been significant changes since 2.32 to the code touched by the bitmanip patches, so a clean patch would seem to involve non-trivial manual backporting. I can try and see how cleanly this patch can be made on top of 2.33. One disadvantage of creating the minimum possible patch is that if you then want to pull more recent changes that might involve further work.

**Comment by imphil** [comment]
Fixed in #11 and #10. Thanks @luismarques!

I'll give this build a try with ibex and then tag and update our toolchain there. After a couple days of soak time we can do the same for OT.
